### ISSUE TITLE
Blocktime difference with running 2 validators

### ISSUE THREAD

**Issue by BenWhiteJam** [paritytech/subport#60] opened 2020-12-07 17:00 UTC
**Team**: Benjamin from equilibrium
**Product**: Parachain
**Stage**: Testnetwork
**Support Needed**: on-time-support
**References Sent**: Yes
**Context**:
When we start 1 node (1 validator) we can process around 1k transactions, but when we start 2 validators 10 tx's make our block 7-8 secs instead of 6 (in normal case) what logs should we look at to understand whats the problem
-> maybe related to https://github.com/paritytech/subport/issues/52?

**Comment by shawntabrizi** [comment] 2020-12-07 18:17
@BenWhiteJam just to clarify, the `10` above should be `1k` too?

Off the top of my head, I would suspect a multi-node network to run slower than a single node network because other nodes on the network have to gossip and import the new block before trying to process the next one.

So if you have two validators, on two different nodes, you have now introduced an overhead to each validator to import and process that block, which will add about 2 seconds of additional compute per full block compared to an empty block...

How specifically are you measuring these timings and what kind of setup have you created?

More details here will help us help you.

**Comment by Veniamin** [comment] 2020-12-09 07:43
We can reproduce an issue with 2 nodes on one machine (so no network issues here) even with dev validators (alice and bob). Yes it is ok that several validators can process less transactions than one, but difference is too big. What logs should we add to understand what part of node is processing slow?

**Comment by Veniamin** [comment] 2020-12-09 07:45
it seems to us that the problem is not in consensus, because changing AURA to BABE dont lead to improvement,

**Comment by shawntabrizi** [comment] 2020-12-10 00:25
I mentioned above that block import from one node to another will be around 2 seconds for a full block, since the default max weight in Substrate is 2 seconds. Imagine that one node generates a block with 2 seconds worth of computation, and another node will have to also do that 2 seconds of computation to verify the block is valid, thus the additional overhead you see.

I do not see that this is a valid "issue" as much as it is just a aspect of the chain.

If you run 2 nodes with empty blocks, you should probably see this overhead disappear.

**Comment by Veniamin** [comment] 2020-12-10 12:44
so the real block time can be random time between 6 and 8 secs?

**Comment by Veniamin** [comment] 2020-12-10 12:47
I just cloned last substrate template https://github.com/substrate-developer-hub/substrate-node-template and reproduced problem on this node. So 60 transfers in 1 block makes block time more than 10 secs

**Comment by Veniamin** [comment] 2020-12-10 12:48
But everything works fine when I started only 1 validator.

**Comment by riusricardo** [comment] 2020-12-10 14:20
@Veniamin Can you provide more details of your testing setup? It will help us to find out what could be happening. 
Did you modify anything in the node template or you were able to reproduce as it is?

Not random but it won't be exactly 6 seconds. It is a targeted block time, some blocks may take less time and some others may take more. As Shawn said, this is also impacted by the network. 
The only situation where blocks are not imported through the block import queue is when you are creating new blocks; When you create the block yourself, you import it directly.

**Comment by Veniamin** [comment] 2020-12-10 15:31
I took node template without any changes, then started alice + bob version

cargo run -- \
  --base-path /tmp/alice \
  --chain=local \
  --alice \
  --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
  --validator \
  --execution=wasm --wasm-execution=compiled

And with help of substrate-subxt generated 60 transfer transactions from alice to bob (with random parameters).

**Comment by shawntabrizi** [comment] 2020-12-10 19:26
Can you show us a screenshot or something of how you are determining the block time is more than 6 seconds?

**Comment by Veniamin** [comment] 2020-12-11 11:06
![image](https://user-images.githubusercontent.com/736337/101896258-bd8c2900-3bb9-11eb-8fc0-d45463349487.png)

and in logs

`
Dec 11 14:03:47.750  INFO ✨ Imported #13 (0x9c29…f2e0)    
Dec 11 14:03:48.092  INFO 🙌 Starting consensus session on top of parent 0x9c29e69d84c25d05a587c589881d4b065e757b91185226615b78a03a9edbf2e0    
Dec 11 14:03:49.016  INFO 💤 Idle (1 peers), best: #13 (0x9c29…f2e0), finalized #10 (0xf6f9…372f), ⬇ 2.8kiB/s ⬆ 2.5kiB/s    
Dec 11 14:03:50.876  INFO 🎁 Prepared block for proposing at 14 [hash: 0x622c640daa4c15ca328bacf6fe2b3a41fdca7393864a0940af383bb84de921d8; parent_hash: 0x9c29…f2e0; extrinsics (56): [0xd257…a108, 0x276e…f750, 0xc8c8…1e5e, 0x0a25…40a3, 0x7e21…25c7, 0x346b…adcc, 0x93b4…b26e, 0xd13c…3f02, 0x36e1…8f06, 0xb8f0…c04d, 0x4166…9dc7, 0xa6d2…698e, 0x4015…8615, 0x7397…9066, 0x0040…1d8f, 0x783a…be10, 0x90b7…0caf, 0x5abf…35a5, 0xa606…c0c0, 0x35e8…78cf, 0xd6d8…0100, 0xef33…c46b, 0x5288…e086, 0x6aed…d07e, 0x65f6…2780, 0x365e…d99b, 0xb978…47a3, 0x2c43…dfad, 0x2cc0…3b91, 0xae60…884f, 0xb4b2…3ee4, 0xe24e…336d, 0x9657…ab6e, 0xce83…22f2, 0xa7af…b647, 0xf3f4…d40b, 0x4d51…70b6, 0xdcc4…b16b, 0xd34f…9804, 0xe232…90d0, 0xaa29…6468, 0xff76…6d9b, 0x433e…0768, 0x5e4f…ed70, 0xb36b…f387, 0x6196…032c, 0xec6e…42e6, 0x9ab5…dbed, 0x21c6…25c4, 0x1051…09a4, 0x54db…ad20, 0xb44f…30e7, 0xf156…975f, 0x5e1b…1a9a, 0xce2f…ea93, 0x1145…0a3d]]    
Dec 11 14:03:50.970  INFO 🔖 Pre-sealed block for proposal at 14. Hash now 0x4c09a4c44570ef5823a5f1459ffc51d88bf50c8ca2cad99a74a3601c532dea9f, previously 0x622c640daa4c15ca328bacf6fe2b3a41fdca7393864a0940af383bb84de921d8.    
Dec 11 14:03:50.973  INFO ✨ Imported #14 (0x4c09…ea9f)    
Dec 11 14:03:54.017  INFO 💤 Idle (1 peers), best: #14 (0x4c09…ea9f), finalized #12 (0x9770…a263), ⬇ 0.9kiB/s ⬆ 4.2kiB/s    
Dec 11 14:03:57.550  INFO ✨ Imported #15 (0xb52c…8a11)    
`

**Comment by danforbes** [comment] 2020-12-16 22:16
I attempted to reproduce this problem on my machine and was not able to. I am working with @Veniamin and some other folks at Parity to potentially get on a screen share and make sure nothing is getting lost in the sauce.

**Comment by Veniamin** [comment] 2020-12-21 07:16
I finally solved the problem. Debug build is working much slower than release and this issue is related only to debug version. I think we can close it for now, because in production should be release version.

**Comment by danforbes** [comment] 2020-12-21 13:36
Thanks for the update, @Veniamin. Please reopen this Issue or create a new one if you have more questions or run into more problems.

**Closed by danforbes** 2020-12-21 13:36 UTC
Labels: help wanted, question
