### ISSUE TITLE
How to avoid transaction loss caused by consensus mechanism

### ISSUE THREAD

**Issue by xtony77** [paritytech/subport#264] opened 2021-11-05 09:19 UTC
We use pallet-babe consensus in substrate, there is a situation that the transaction hash can be found in the best block, but it cannot be found in the finalized block.

How to avoid this situation? Can it be solved by add more validator?

Our current practice is to re-send the transaction when we find this situation, but it is very troublesome. Are there any good suggestions?

**Comment by NukeManDan** [comment] 2021-11-07 20:26
This is _the intended behavior_: BABE has forks in the network that _eventually_ finalized by GRANDPA for Polkadot (as an example). It is highly intended to wait for finalization before being assured that a specific block will be included in the canonical chain. 
More info:
https://research.web3.foundation/en/latest/polkadot/block-production.html
https://wiki.polkadot.network/docs/build-protocol-info#transaction-mortality

**Closed by NukeManDan** 2021-11-07 20:26 UTC
